// <auto-generated />
namespace MD2Contact.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Contacts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Contacts));
        
        string IMigrationMetadata.Id
        {
            get { return "201911192327258_Contacts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
